name: Refresh

on:
  schedule:
    - cron: "0 3 * * *" # Runs every day at 3am

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $BOT_TOKEN"
        env:
          BOT_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
